import process from 'process'
import { readFileSync, cpSync, mkdirSync } from 'fs'
import { builtinModules } from 'module'

import esbuild from 'esbuild'
import sveltePlugin from 'esbuild-svelte'
import sveltePreprocess from 'svelte-preprocess'

// Read version from manifest.json
const manifest = JSON.parse(readFileSync('./manifest.json', 'utf8'))
const version = manifest.version

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

// Copies the WASM Typst compiler and its hard-requirement assets (the
// cmarker package, a default font — both required for compilation to
// succeed at all, not optional) to the repo root, alongside main.js. These
// ship as separate files, not inlined into main.js, per the plugin-relative
// resolution pattern TypstRunner.ts uses at runtime (see GitHub issue #77's
// findings — require.resolve()-based lookup does not work once main.js is
// installed with no node_modules nearby).
function copyTypstAssets() {
  mkdirSync('typst-cmarker', { recursive: true })
  mkdirSync('typst-fonts', { recursive: true })
  cpSync(
    'node_modules/@myriaddreamin/typst-ts-web-compiler/pkg/typst_ts_web_compiler_bg.wasm',
    'typst-compiler.wasm',
  )
  cpSync('vendor/typst/cmarker', 'typst-cmarker', { recursive: true })
  cpSync('vendor/typst/fonts', 'typst-fonts', { recursive: true })
}
copyTypstAssets()

const prod = process.argv[2] === 'production'

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@electron/remote',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    // typst.ts's renderer.mjs dynamically imports this for live-preview
    // rendering, which Lighthouse never calls (only createTypstCompiler(),
    // for PDF export) — external so esbuild doesn't try to resolve a
    // package we deliberately didn't install.
    '@myriaddreamin/typst-ts-renderer',
    ...builtinModules,
    ...builtinModules.map((m) => `node:${m}`),
  ],
  format: 'cjs',
  target: 'es2020',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
  define: {
    // Inject version for tools manifest URL
    __LIGHTHOUSE_VERSION__: JSON.stringify(version),
  },
  loader: {
    // Import .css files as raw text strings (used by export styles registry)
    '.css': 'text',
  },
  plugins: [
    sveltePlugin({
      preprocess: sveltePreprocess(),
      compilerOptions: { css: 'injected' },
    }),
  ],
})

if (prod) {
  await context.rebuild()
  process.exit(0)
} else {
  await context.watch()
}
